### ISSUE TITLE
MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by Ketanmk** [JuanDMeGon/myownapi#1]
when I post something in vehicles it gives an error MethodNotAllowedHttpException 
  <abbr title="Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException">MethodNotAllowedHttpException</abbr> in
                    <a title="C:\xampp\htdocs\MyOwnAPI\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php line 218" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">RouteCollection.php line 218</a>:

**Comment by Ketanmk** [comment]
Error comes in MyOwnAPI Project 
please help to solve this problem.....

**Comment by JuanDMeGon** [comment]
Hello,
This is not an issue with the code. 
Please post a question in the platform where you are taking the course and I will be glad to answer. 

Best wishes.
